### ISSUE TITLE
Yo como cocina - Quiero poder ingresar a la plataforma - (login)

### ISSUE THREAD

**Issue by MaxiZet** [4GeeksAcademy/comedor_anda_grupo4#2]
Historia de Usuario: Ingreso a la Plataforma para Cocina

Título: Ingresar a la plataforma (Cocina)
Como: Miembro del equipo de cocina
Quiero: Poder ingresar a la plataforma mediante un sistema de login
Para que: Pueda gestionar los menús y acceder a las herramientas de administración

Criterios de aceptación:

El miembro del equipo de cocina debe poder ingresar su correo electrónico y su contraseña en un formulario de inicio de sesión.
Si las credenciales son correctas, se permitirá el acceso y se redirigirá al usuario a su panel de cocina.
Si las credenciales son incorrectas, se mostrará un mensaje de error claro: "Usuario o contraseña incorrectos".
Debe haber una opción para recuperar la contraseña en caso de que el miembro del equipo de cocina la haya olvidado.
La sesión debe mantenerse activa mientras dure su uso, con un tiempo de expiración configurado por seguridad (ej.: 30 minutos de inactividad).
Notas técnicas:

Utilizar autenticación basada en roles, asegurando que el miembro de cocina acceda solo a las secciones pertinentes.
Implementar autenticación segura mediante tokens (JWT o similar).
Validar los datos de inicio de sesión en el backend, protegiendo contra ataques como SQL Injection o fuerza bruta.

**Comment by MaxiZet** [comment]
Historia de Usuario: Ingreso a la Plataforma para Cocina

Título: Ingresar a la plataforma (Cocina)
Como: Miembro del equipo de cocina
Quiero: Poder ingresar a la plataforma mediante un sistema de login
Para que: Pueda gestionar los menús y acceder a las herramientas de administración

Criterios de aceptación:

El miembro del equipo de cocina debe poder ingresar su correo electrónico y su contraseña en un formulario de inicio de sesión.
Si las credenciales son correctas, se permitirá el acceso y se redirigirá al usuario a su panel de cocina.
Si las credenciales son incorrectas, se mostrará un mensaje de error claro: "Usuario o contraseña incorrectos".
Debe haber una opción para recuperar la contraseña en caso de que el miembro del equipo de cocina la haya olvidado.
La sesión debe mantenerse activa mientras dure su uso, con un tiempo de expiración configurado por seguridad (ej.: 30 minutos de inactividad).
Notas técnicas:

Utilizar autenticación basada en roles, asegurando que el miembro de cocina acceda solo a las secciones pertinentes.
Implementar autenticación segura mediante tokens (JWT o similar).
Validar los datos de inicio de sesión en el backend, protegiendo contra ataques como SQL Injection o fuerza bruta.

**Comment by embrana** [comment]
![Image](https://github.com/user-attachments/assets/2360f4fc-21c5-480d-8e1a-64361eea79f6)

**Comment by SamuelCarmona83** [comment]
Esto esta listo @MaxiZet ?
