### ISSUE TITLE
Yo como cliente - Quiero poder ver el listado de menús disponibles hoy para poder seleccionar - (selección menú)

### ISSUE THREAD

**Issue by Machado123LV** [4GeeksAcademy/comedor_anda_grupo4#3]
Historia de Usuario: Selección de Menú
Título: Ver el listado de menús disponibles hoy

Como: Cliente
Quiero: Poder ver el listado de menús disponibles hoy
Para que: Pueda seleccionar el que prefiera

Criterios de aceptación:

El cliente debe poder visualizar un listado claro y organizado de los menús disponibles en el día.
Cada menú debe incluir detalles relevantes como nombre, descripción, precio y disponibilidad.
El listado debe ser fácil de navegar, con la opción de filtrar o buscar según preferencias (ej.: vegetariano, sin gluten, etc.).
El cliente debe poder seleccionar un menú para proceder a la siguiente etapa (ej.: confirmación, pago, etc.).
Notas técnicas:

La información de los menús debe cargarse dinámicamente desde una base de datos actualizada.
Implementar una interfaz responsiva para facilitar la navegación desde dispositivos móviles.
Utilizar un endpoint REST para recuperar los datos de los menús, asegurando un tiempo de respuesta óptimo.

**Comment by embrana** [comment]
![Image](https://github.com/user-attachments/assets/25c1ea60-3314-4db0-9b51-9d24124199d7)
