### ISSUE TITLE
Ingreso a la plataforma como administrador

### ISSUE THREAD

**Issue by Elibar55** [4GeeksAcademy/comedor_anda_grupo4#4]
Como administrador, quiero poder ingresar a la plataforma mediante un sistema de inicio de sesión, para acceder a las funcionalidades y herramientas administrativas disponibles.

Criterios de Aceptación
Formulario de Login:

El sistema debe mostrar un formulario con los campos "Usuario" y "Contraseña".
Debe haber un botón etiquetado como "Iniciar Sesión".
Validación de Credenciales:

Si las credenciales son correctas, el usuario será redirigido al panel de administrador.
Si las credenciales son incorrectas, debe mostrarse un mensaje de error: "Usuario o contraseña incorrectos".
Requerimientos de Seguridad:

Las contraseñas deben ser encriptadas al ser enviadas.

Persistencia de Sesión:

El sistema debe mantener la sesión activa por 1 hora si el usuario selecciona "Recordarme".
Si no se selecciona "Recordarme", la sesión expirará tras 30 minutos de inactividad.
Acceso Restringido:

Solo usuarios con roles de administrador pueden acceder al panel de administración. Otros roles recibirán un mensaje de acceso denegado: "No tienes permiso para acceder a esta sección".
Notas Técnicas
Front-end:

Implementar el formulario con campos validados (HTML5 o librerías como Formik en React).
Usar Bootstrap para el diseño, asegurando compatibilidad móvil.
Back-end:

Crear un endpoint POST /login para autenticar usuarios.
Implementar autenticación con JWT.
Pruebas:

Realizar pruebas de integración para confirmar el flujo completo de login.
Incluir casos de prueba para credenciales inválidas, cuenta bloqueada y roles sin acceso.

**Comment by embrana** [comment]
![Image](https://github.com/user-attachments/assets/245a3ce9-c88f-42b1-8028-91c988ec3dec)
